name: toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - jupyter
  - pip
  - pip:
      - absl-py==2.1.0
      - altair==5.3.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - coverage==7.5.1
      - dm-tree==0.1.8
      - etils==1.8.0
      - flatbuffers==24.3.25
      - fsspec==2024.5.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - grpcio==1.63.0
      - h5py==3.11.0
      - idna==3.7
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pluggy==1.5.0
      - promise==2.3
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydeck==0.9.1
      - pytest==8.2.1
      - pytest-cov==5.0.0
      - pytest-timeout==2.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - smmap==5.0.1
      - sqlalchemy==1.4.0
      - streamlit==1.34.0
      - tenacity==8.3.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-datasets==4.9.4
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.15.0
      - tensorflow-recommenders==0.7.3
      - termcolor==2.4.0
      - toml==0.10.2
      - toolz==0.12.1
      - tqdm==4.66.4
      - typing-extensions==4.5.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - watchdog==4.0.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.18.1
