name: toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.3.11=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.1=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.24.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h1ea47a8_0
  - krb5=1.21.2=heb0366b_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.0=hcfcfb64_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py311haa95532_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311ha68e1ae_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.11.9=he1021f5_0
  - python_abi=3.11=2_cp311
  - pywin32=306=py311h12c1d0e_2
  - pyzmq=26.0.3=py311h484c95c_0
  - setuptools=69.5.1=py311haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4=py311ha68e1ae_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py311haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=he1f189c_4
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.1.0
      - altair==5.3.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - coverage==7.5.1
      - dm-tree==0.1.8
      - etils==1.8.0
      - flatbuffers==24.3.25
      - fsspec==2024.5.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - grpcio==1.63.0
      - h5py==3.11.0
      - idna==3.7
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pluggy==1.5.0
      - promise==2.3
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydeck==0.9.1
      - pytest==8.2.1
      - pytest-cov==5.0.0
      - pytest-timeout==2.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - smmap==5.0.1
      - sqlalchemy==1.4.0
      - streamlit==1.34.0
      - tenacity==8.3.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-datasets==4.9.4
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.15.0
      - tensorflow-recommenders==0.7.3
      - termcolor==2.4.0
      - toml==0.10.2
      - toolz==0.12.1
      - tqdm==4.66.4
      - typing-extensions==4.5.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - watchdog==4.0.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.18.1
variables:
  PYTHONPATH: .
  pytest: ''
prefix: D:\App\anaconda\envs\toolkit
